/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <RippleGreetingImplFactory.hpp>
#include "RippleGreetingImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include "MediaPipelineImpl.hpp"

#define GST_CAT_DEFAULT kurento_ripple_greeting_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoRippleGreetingImpl"

namespace kurento
{
namespace module
{
namespace ripplegreeting
{

RippleGreetingImpl::RippleGreetingImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) : OpenCVFilterImpl (config, std::dynamic_pointer_cast<MediaPipelineImpl> (mediaPipeline))

{
}

MediaObjectImpl *
RippleGreetingImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new RippleGreetingImpl (config, mediaPipeline);
}

RippleGreetingImpl::StaticConstructor RippleGreetingImpl::staticConstructor;

RippleGreetingImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* ripplegreeting */
} /* module */
} /* kurento */
