/* Autogenerated with kurento-module-creator */

#include "RippleGreetingOpenCVImpl.hpp"
#include <KurentoException.hpp>

namespace kurento
{
namespace module
{
namespace ripplegreeting
{

RippleGreetingOpenCVImpl::RippleGreetingOpenCVImpl ()
{
}

/*
 * This function will be called with each new frame. mat variable
 * contains the current frame. You should insert your image processing code
 * here. Any changes in mat, will be sent through the Media Pipeline.
 */
void RippleGreetingOpenCVImpl::process (cv::Mat &mat)
{
  // FIXME: Implement this
  //throw KurentoException (NOT_IMPLEMENTED, "RippleGreetingOpenCVImpl::process: Not implemented");

   cv::Point textOrg(100, 100);
   putText( mat, "Hello from Ripple", textOrg, 1, 2, cv::Scalar(0, 0, 0) );
}



} /* ripplegreeting */
} /* module */
} /* kurento */
