/* Autogenerated with kurento-module-creator */

#ifndef __RIPPLE_GREETING_INTERNAL_HPP__
#define __RIPPLE_GREETING_INTERNAL_HPP__

#include "RippleGreeting.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace ripplegreeting
{

class RippleGreetingConstructor
{
public:
  RippleGreetingConstructor() = default;
  ~RippleGreetingConstructor() = default;

  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaPipeline> getMediaPipeline ();

  void setMediaPipeline (std::shared_ptr<MediaPipeline> mediaPipeline) {
    this->mediaPipeline = mediaPipeline;
  }

private:
  std::shared_ptr<MediaPipeline> mediaPipeline;
};

} /* ripplegreeting */
} /* module */
} /* kurento */

#endif /*  __RIPPLE_GREETING_INTERNAL_HPP__ */
