/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "RippleGreetingImpl.hpp"
#include "RippleGreetingImplFactory.hpp"
#include "RippleGreetingInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{
namespace module
{
namespace ripplegreeting
{

MediaObjectImpl *RippleGreetingImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  RippleGreetingConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
RippleGreetingImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  OpenCVFilterImpl::invoke (obj, methodName, params, response);
}

bool
RippleGreetingImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return OpenCVFilterImpl::connect (eventType, handler);
}

void
RippleGreetingImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'RippleGreetingImpl' cannot be deserialized as an object");
  }
}
} /* ripplegreeting */
} /* module */
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::module::ripplegreeting::RippleGreetingImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::module::ripplegreeting::RippleGreetingImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::module::ripplegreeting::RippleGreetingImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::module::ripplegreeting::RippleGreeting> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::module::ripplegreeting::RippleGreetingImpl> aux = std::dynamic_pointer_cast<kurento::module::ripplegreeting::RippleGreetingImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::module::ripplegreeting::RippleGreeting> (aux);
}

} /* kurento */
