/* Autogenerated with kurento-module-creator */

#ifndef __RIPPLE_GREETING_IMPL_FACTORY_HPP__
#define __RIPPLE_GREETING_IMPL_FACTORY_HPP__

#include "RippleGreetingImpl.hpp"
#include "OpenCVFilterImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace ripplegreeting
{

class RippleGreetingImplFactory : public virtual OpenCVFilterImplFactory
{
public:
  RippleGreetingImplFactory() = default;

  std::string getName() const override {
    return "RippleGreeting";
  };

private:

  MediaObjectImpl *createObjectPointer (
      const boost::property_tree::ptree &conf,
      const Json::Value &params) const override;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* ripplegreeting */
} /* module */
} /* kurento */

#endif /*  __RIPPLE_GREETING_IMPL_FACTORY_HPP__ */
