/* Autogenerated with kurento-module-creator */

#include "RippleGreetingImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace ripplegreeting
{

void dummyRipplegreeting ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<RippleGreeting> object;

    s.SerializeNVP (object);
  }
}

} /* ripplegreeting */
} /* module */
} /* kurento */
