/* Autogenerated with kurento-module-creator */

#ifndef __RIPPLE_GREETING_HPP__
#define __RIPPLE_GREETING_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "OpenCVFilter.hpp"

namespace kurento
{
namespace module
{
namespace ripplegreeting
{
class RippleGreeting;
} /* ripplegreeting */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::ripplegreeting::RippleGreeting> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace ripplegreeting
{
class RippleGreeting : public virtual OpenCVFilter
{

public:
  RippleGreeting() = default;
  ~RippleGreeting() override = default;


  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

};

} /* ripplegreeting */
} /* module */
} /* kurento */

#endif /*  __RIPPLE_GREETING_HPP__ */
